import fs from 'fs/promises';
import path from 'path';
import { scanProject, ProjectProfile } from './init-scanner.js';
import { TasteEntry, saveProjectTaste, saveGlobalTaste, loadGlobalTaste } from './taste.js';

export async function handleInitCommand(): Promise<void> {
  const root = process.cwd();
  const agentsDir = path.join(root, '.agent');

  console.log('\n🔍 Scanning project...');
  const profile = await scanProject(root);

  await fs.mkdir(path.join(agentsDir, 'taste'), { recursive: true });
  await fs.mkdir(path.join(agentsDir, 'modules'), { recursive: true });

  console.log('📝 Writing project profile (project.md)...');
  await fs.writeFile(path.join(agentsDir, 'project.md'), generateProjectMd(profile));

  console.log('🤖 Writing agent guidance (agents.md)...');
  await fs.writeFile(path.join(agentsDir, 'agents.md'), generateAgentsMd(profile));

  console.log('📦 Writing module documentation...');
  const seenModules = new Set<string>();
  for (const mod of profile.modules) {
    if (!seenModules.has(mod.name)) {
      seenModules.add(mod.name);
      await fs.writeFile(path.join(agentsDir, 'modules', `${mod.name}.md`), generateModuleMd(mod, profile));
    }
  }

  console.log('🎯 Writing taste preferences...');
  const tasteEntries = deriveTasteEntries(profile);
  await saveProjectTaste(tasteEntries, root);

  const globalExisting = await loadGlobalTaste();
  if (globalExisting.length === 0) {
    await saveGlobalTaste([]);
  }

  console.log('\n✅ Initialization complete!');
  console.log(`   📁 .agent/`);
  console.log(`      ├── project.md`);
  console.log(`      ├── agents.md`);
  console.log(`      ├── taste/`);
  console.log(`      │   └── project-taste.md`);
  console.log(`      └── modules/`);
  for (const mod of profile.modules.slice(0, 5)) {
    console.log(`          └── ${mod.name}.md`);
  }
  if (profile.modules.length > 5) {
    console.log(`          └── ... and ${profile.modules.length - 5} more`);
  }
  console.log('');
}

function generateProjectMd(profile: ProjectProfile): string {
  const lines: string[] = [
    `# ${profile.name} — Project Overview`,
    '',
    `Auto-generated by \`/init\` on ${new Date().toISOString().split('T')[0]}.`,
    'Run `/init` again to rescan and update.',
    '',
    '## Tech Stack',
    `- **Language:** ${profile.language}`,
    `- **Languages detected:** ${profile.languages.join(', ')}`,
    `- **Frameworks:** ${profile.frameworks.join(', ') || '(none detected)'}`,
    `- **Build tool:** ${profile.buildTool}`,
    `- **Test frameworks:** ${profile.testFrameworks.join(', ') || '(none detected)'}`,
    `- **Source directories:** ${profile.sourceDirs.map(d => path.relative(process.cwd(), d)).join(', ') || '(none)'}`,
    '',
    '## Project Stats',
    `- **Total source files:** ${profile.fileCount}`,
    `- **Modules detected:** ${profile.moduleCount}`,
    '',
  ];

  if (profile.features.length > 0) {
    lines.push('## Features Detected');
    for (const f of profile.features) {
      lines.push(`- ${f}`);
    }
    lines.push('');
  }

  if (profile.conventions.length > 0) {
    lines.push('## Code Conventions');
    for (const c of profile.conventions) {
      lines.push(`- ${c}`);
    }
    lines.push('');
  }

  if (profile.traits.length > 0) {
    lines.push('## Detected Traits');
    for (const t of profile.traits) {
      lines.push(`- **${t.name}** (confidence: ${(t.confidence * 100).toFixed(0)}%) — ${t.evidence}`);
    }
    lines.push('');
  }

  if (profile.modules.length > 0) {
    lines.push('## Module Structure');
    const seen = new Set<string>();
    for (const mod of profile.modules) {
      if (!seen.has(mod.name)) {
        seen.add(mod.name);
        lines.push(`- \`${mod.path}/\` — ${mod.files.length} files`);
      }
    }
    lines.push('');
  }

  return lines.join('\n');
}

function generateAgentsMd(profile: ProjectProfile): string {
  return [
    '# Agent Guidance for ' + profile.name,
    '',
    'Auto-generated by `/init`. Update this file to guide the AI agent on how to work with this project.',
    '',
    '## Project Structure',
    `This is a ${profile.language} project using ${profile.frameworks.join(', ') || 'detected frameworks'} with ${profile.buildTool} as the build tool.`,
    `Source code is organized into ${profile.moduleCount} modules under ${profile.sourceDirs.map(d => path.relative(process.cwd(), d)).join(', ') || 'the project root'}.`,
    '',
    '## Key Files',
    generateKeyFilesSection(profile),
    '',
    '## Conventions',
    profile.conventions.length > 0
      ? profile.conventions.map(c => `- ${c}`).join('\n')
      : '- (Conventions detected during init — review and update as needed)',
    '',
    '## Common Tasks',
    '- Run `npm test` to execute tests',
    '- Run `npm run dev` for development server',
    '- Run `npm run build` to build the project',
    '',
    '## Notes for the Agent',
    '- Always read existing code patterns before making changes',
    '- Prefer the module\'s existing style when adding new code',
    '- Check `project.md` and `taste/` for project-specific preferences',
    '- Check `modules/` for per-module context',
  ].join('\n');
}

function generateKeyFilesSection(profile: ProjectProfile): string {
  const items: string[] = [];
  if (profile.language === 'TypeScript' || profile.language === 'JavaScript') {
    items.push('- `package.json` — dependencies and scripts');
    if (profile.frameworks.some(f => f.includes('Next'))) items.push('- `next.config.*` — Next.js configuration');
    if (profile.frameworks.some(f => f.includes('Vite'))) items.push('- `vite.config.*` — Vite configuration');
  }
  if (profile.modules.length > 0) {
    const modPaths = [...new Set(profile.modules.map(m => m.path))].slice(0, 5);
    for (const mp of modPaths) {
      items.push(`- \`${mp}/\` — module directory`);
    }
  }
  return items.join('\n');
}

function generateModuleMd(mod: { name: string; path: string; files: string[] }, profile: ProjectProfile): string {
  const lines: string[] = [
    `# Module: ${mod.name}`,
    '',
    `**Path:** \`${mod.path}/\``,
    `**Files:** ${mod.files.length}`,
    '',
    '## Files',
  ];
  // Show up to 30 files
  const displayFiles = mod.files.slice(0, 30);
  for (const f of displayFiles) {
    const rel = path.relative(process.cwd(), f);
    const stat = f.endsWith('.md') ? 'documentation' : f.endsWith('.test.') ? 'test' : f.endsWith('.spec.') ? 'test' : 'source';
    lines.push(`- \`${rel}\` — ${stat}`);
  }
  if (mod.files.length > 30) {
    lines.push(`- ... and ${mod.files.length - 30} more files`);
  }
  return lines.join('\n');
}

function deriveTasteEntries(profile: ProjectProfile): TasteEntry[] {
  const entries: TasteEntry[] = [];

  for (const t of profile.traits) {
    entries.push({ preference: t.name, confidence: t.confidence, source: t.evidence, category: categorizeTrait(t.name) });
  }

  if (profile.language === 'TypeScript') {
    entries.push({ preference: 'uses TypeScript for type safety', confidence: 0.9, source: 'detected from project config', category: 'code-style' });
  }

  return entries;
}

function categorizeTrait(name: string): TasteEntry['category'] {
  const lower = name.toLowerCase();
  if (lower.includes('css') || lower.includes('tailwind') || lower.includes('styling')) return 'ui';
  if (lower.includes('framework') || lower.includes('react') || lower.includes('vue') || lower.includes('angular') || lower.includes('svelte') || lower.includes('next') || lower.includes('nuxt')) return 'framework';
  if (lower.includes('class') || lower.includes('function') || lower.includes('semicolon') || lower.includes('typescript')) return 'code-style';
  if (lower.includes('architecture') || lower.includes('pattern') || lower.includes('component')) return 'architecture';
  if (lower.includes('lint') || lower.includes('format') || lower.includes('test')) return 'workflow';
  return 'other';
}
